version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - setup_remote_docker

      
  testowanie_serwera:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run:
          command: npm install
          working_directory: ./server  
      - run:
          name: Running server tests
          command: npm test
          working_directory: ./server
                    
  testowanie_klienta:
    executor:
      name: node/default
    steps:
      - checkout       
      - run:
          command: npm install
          working_directory: ./client      
      - run:
          name: Running server tests
          command: npm test
          working_directory: ./client
          
  create_docker_images:
    machine: true
    steps:
      - checkout          
      - run:
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "ewelinaszczupak" --password-stdin
            sudo docker build ./db -t ewelinaszczupak/database_image_2020
            sudo docker push ewelinaszczupak/database_image_2020:latest
      - run:
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "ewelinaszczupak" --password-stdin
            sudo docker build ./server -t ewelinaszczupak/server_image_2020
            sudo docker push ewelinaszczupak/server_image_2020
      - run:
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "ewelinaszczupak" --password-stdin
            sudo docker build ./client -t ewelinaszczupak/client_image_2020
            sudo docker push ewelinaszczupak/client_image_2020

          
workflows:
    build-and-test:
      jobs:
        - build:
          filters:
            branches:
              only:
                - master
        - testowanie_serwera:
            filters:
              branches:
                only:
                  - master
            requires:
                - build
        - testowanie_klienta:
            filters:
              branches:
                only:
                  - master
            requires:
                - build
                
        - create_docker_images:
            requires:
              - testowanie_serwera
              - testowanie_klienta
